# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fc2a45fe912fd28e5b2d5ec824e38ff2fa136cbfd2f19e541b694b7287b300631be2524125d2dfc599d85fc44bea653c45161d08ac6a46e7a1fd92b945aec995

test:
  secret_key_base: 2fcc205254e2337608a652af395a3869e4ee9c4484159065a51a3e0b377e12523308700b6904cb9b33febf1cef31c7624912883d5b451649a5832a23e6860230

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
